run-android:
	cd Frontend && npm run android

run-ios:
	cd Frontend && npm run ios -- --simulator=''

server:
	# cd api && python manage.py runserver 0.0.0.0:8081
	# .env/bin/activate && cd api && python manage.py runserver
	cd api && python3 manage.py runserver 0.0.0.0:8000

	